### ISSUE TITLE
Feature request: export scanned parts

### ISSUE THREAD

**Issue by rickyelopez** [codelv/inventory#2]
This is really cool! I would love to use this app in order to scan all my parts, and then export that to further import it into an InvenTree instance. Is there any way you could add a feature to export to a file of some kind?

**Comment by frmdstryr** [comment]
It uses an sqlite database. Would having the ability to export that be good enough?

**Comment by frmdstryr** [comment]
Added sqlite export in https://github.com/codelv/inventory/commit/98415e14b98a30a67cc5a7205b4b6ca09fd77ea4. If you need the table as a csv you can open it with https://sqlitebrowser.org/ and export the parts table as csv.

Thanks!

**Comment by rickyelopez** [comment]
Yup that works for me, thank you!!

**Comment by rickyelopez** [comment]
Sorry I'm not super familiar with this, when will the update show up on F-Droid? It's still showing v1.0.2 as the newest version for me... Thanks!
