### ISSUE TITLE
[Feature request] Older one-dimensional barcodes?

### ISSUE THREAD

**Issue by terminator356** [codelv/inventory#4]
Nice app! It works with my modern DigiKey parts. 

It appears to only support QR codes. Correct?
Wondering if it would be too difficult to add older 1-D bar code support,
 particularly with older DigiKey parts, of which I have many.

One more question: Does the app support Mouser parts at all?
They seem to be a bit more difficult, from what I read.

Thanks for this helpful gem.

**Comment by frmdstryr** [comment]
The reason it doesn't do 1D barcodes there is no way to know if the barcode was an MPN or some other random thing like a order number. 

For some of my older reels/unlabeled parts I used inkscape's qr code generator and printed out labels for them. For the LCSC format to scan all it needs is a string like `{pm: the-mpn, qty: 1}` No quotes or anything. 

Unfortunately I don't have any parts from mouser to test with. If the barcode has some format that it can detect that it's an MPN you can also add another condition here https://github.com/codelv/inventory/blob/master/app/src/main/java/com/codelv/inventory/Models.kt#L393 (eg `else if (value) { result = Part(id=0, mpn=value)  }`  (or send the scan text and I can add it)

**Comment by terminator356** [comment]
Ah yes. Sorry for the noise on that one.
I checked a bunch of old DK parts, the barcodes all look the same, having a number underneath.
Here is an old DK part, when I scan it with BinaryEye (from F-Droid), the string simply says the same
 number the photo shows under the barcode, so unfortunately it seems unhelpful, as it likely
 points to some order number or DK internal reference number or something:
![20231105_202536](https://github.com/codelv/inventory/assets/5422362/c5e9e8e8-d27d-4be5-914b-6ffc0cb29152)

I scanned a modern Mouser part bag QR with Inventory:
Wow! 
It recognized it and added it to the database, complete with manufacturer (T.I.).
Funny, I clicked on go to website and it found it on DK, and even **imported the info from DK**, 
since DK lists it (but it's not normally available to buy):
![20231105_202432](https://github.com/codelv/inventory/assets/5422362/fdfc1be8-43cb-4c84-be00-09ff95e170a8)

With older Mouser parts, there are several barcodes on the bag for various fields,
 and I believe that was the difficulty in scanning that I was referring to before.
I could post pictures if you like.

**Comment by terminator356** [comment]
> I could post pictures if you like.

Ehm... Actually they are in the picture above.

**Comment by terminator356** [comment]
> It recognized it and added it to the database, complete with manufacturer (T.I.).

Ehm... Actually that's the _supplier_ field, not manufacturer.
The manufacturer field does correctly say Nichicon, I think after I imported the info from DK.

Thanks.

**Comment by frmdstryr** [comment]
You can import data for any part by setting the mpn or sku, then clicking import. Import just does a search on DK or LSCS (depending on the supplier field) of the sku or mpn (sku preferred if both are set) and will import if it finds a single result (only blank fields, it will not overwrite). 

If you click the scan list and find the mpn from the 1D barcode I believe you can copy the text and paste that into a new part. Maybe a separate button to "import as mpn" from the scan list would be better?

As you discovered the supplier auto detection it doesn't work correctly...

**Comment by terminator356** [comment]
Alert! DK's QR labels have changed.

For several months in my parts orders they have inserted a sheet of paper informing of expanded QR codes.
I ignored it of course, not being interested in labels at the time. 
But now I _am_ interested, and last night I re-read the paper and checked the new codes
Here is the announcement, I wonder if you have seen it:
[https://forum.digikey.com/t/new-labels-on-product/19862](url)

Here is an example of the older QR code:
![20231106_112059](https://github.com/codelv/inventory/assets/5422362/72ef710a-fcdc-4795-aa5e-1db4b4fc7946)

When scanned with Inventory, all is OK including the 'Supplier' field which says "DigiKey".

Now here is an example of the new code:
![20231106_112208](https://github.com/codelv/inventory/assets/5422362/635df66b-a5f3-47c5-9e99-9da8da499d0f)

Here is what BinaryEye tells me is the scanned string of that new QR code:
`[)>␞06␝P493-11021-1-ND␝1PUFW1HR47MDD1TD␝30P493-11021-1-ND␝K␝1K83772208␝10K100741682␝9D2315␝1T340052-00␝11K1␝4LMY␝Q10␝11ZPICK␝12Z4317926␝13Z999999␝20Z000000000000000000000000000000000000000000000000000000000000000000000000000000000000`

When I scan this new part with Inventory, all seems OK except for the 'Supplier' field which again says "TI".

Wonder if that could be fixed?
Seems like the same problem as the Mouser QR code (above)?
Seems like both DK and Mouser now use the same, or similar format?

To fix this problem, and/or if you are interested in providing full Mouser QR code support,
 if automatic detection of supplier is a problem, might I suggest that users (including me)
 would not mind at all if there was a supplier 'Mode' setting: 'DigiKey', 'Mouser', 'LSCS', and even 'Automatic'
 if you feel so bold.
Users would choose 'Mouser' mode, then scan all their Mouser parts, then switch to 'DigiKey' mode
 and scan all their DK parts. Thus all the scanned parts would have the correct 'Supplier' field.
Something like that...

Thanks for your help and attention.

**Comment by frmdstryr** [comment]
I pushed an update (v1.0.6) that disables setting the supplier since I'm not sure how to auto detect that. 

If you click on edit and put "Mouser" in the supplier field, then import, it will pull the data from mouser. If the supplier is blank it still uses digikey.

**Comment by terminator356** [comment]
F-Droid update came in.

Tested OK. Thanks!

Currently trying to set up build chain here on opensuse, to see if I can
 help in some way, or at least follow how it works.

Closing for now if that's OK...
